[dependencies]
actix-web = "4"
reqwest = { version = "0.11", features = ["json"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
rustls = "0.20"
openssl = { version = "0.10", features = ["vendored"] }
